targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = [
    # TODO: Investigate proper removal for stb_truetype
    "RUSTSEC-2020-0020",
    
    # Might be maintained by BurntSushi, albeit passively.
    "RUSTSEC-2020-0077",
    
    # We don't build on linux, so this is fine.
    # TODO: Find way to remove xcb from dependency tree.
    "RUSTSEC-2020-0097",
    "RUSTSEC-2021-0019",
    
    # TODO: Find way to remove old mio from winit?
    "RUSTSEC-2020-0016",
]

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "ISC", "Unlicense", "Zlib", "CC0-1.0", "BSD-3-Clause" ]
exceptions = []

[bans]
multiple-versions = "deny"
highlight = "all"
skip = [
    # Blocked on glutin being bumped, which is blocked on winit fixing high cpu usage on certain platforms. Dammit winit.
    { name = "unicode-xid", version = "0.1.0" },
    { name = "rusttype", version = "0.7.9" },
    { name = "quote", version = "0.6.13" },
    { name = "proc-macro2", version = "0.4.30" },
    { name = "libloading", version = "0.5.2" },
    { name = "gl_generator", version = "0.13.1" },
    
    # Blocked on png bumping miniz_oxide
    { name = "miniz_oxide", version = "0.3.7" },
    
    # Blocked on updating conrod_core and winit
    { name = "rusttype", version = "0.9.2" },
    
    # Blocked on updating bindgen to 0.55.x, crossbeam, log, nix, and parking_lot_core
    { name = "cfg-if", version = "0.1.10" },
    
    # Blocked on updating rusttype to 0.9.x
    { name = "crossbeam-deque", version = "0.7.3" },
    { name = "crossbeam-epoch", version = "0.8.2" },
    { name = "crossbeam-utils", version = "0.7.2" },
    { name = "memoffset", version = "0.5.6" },
    
    # Blocked on removing old mio from winit
    { name = "winapi", version = "0.2.8" },
    
    # Blocked on updating copypasta in conrod 
    { name = "wayland-sys", version = "0.23.6" },
    { name = "wayland-scanner", version = "0.23.6" },
    { name = "wayland-protocols", version = "0.23.6" },
    { name = "wayland-commons", version = "0.23.6" },
    { name = "wayland-client", version = "0.23.6" },
    { name = "smithay-client-toolkit", version = "0.6.6" },
    { name = "andrew", version = "0.2.1" },
    { name = "nix", version = "0.14.1" },
    
    # Blocked on updating bindgen in steamworks-rs
    { name = "nom", version = "5.1.2" },
    
    # Blocked on winit updating nix to 0.20.x
    { name = "nix", version = "0.18.0" },
    
    # Blocked on smithay-client-toolkit updating dlib to 0.5.x
    { name = "dlib", version = "0.5.0" },
    { name = "libloading", version = "0.6.7" },
    
    # Blocked on winit and glutin actually agreeing on something
    { name = "cocoa", version = "0.23.0" },
    { name = "core-foundation", version = "0.7.0" },
    { name = "core-graphics", version = "0.19.2" },
    { name = "core-foundation-sys", version = "0.7.0" },
]

# Mostly soundness denies since the advisory lacks a section for soundess bugs
deny = [        
    # https://github.com/RustSec/advisory-db/pull/293
    # NOTE: May be sound in the future: https://github.com/RustSec/advisory-db/pull/293#issuecomment-641898680
    { name = "rio", version = "*" },

    # https://github.com/RustSec/advisory-db/issues/299
    { name = "smallvec", version = "<0.6.13" },
    
    # https://github.com/RustSec/advisory-db/pull/268
    { name = "plutonium", version = "*" },
    
    # https://github.com/RustSec/advisory-db/pull/308
    { name = "traitobject", version = "*" },
    
    # https://github.com/RustSec/advisory-db/issues/305
    { name = "rental", version = "*" },
    
    # Appears to be moving towards integrating rio more tightly for io_uring support
    { name = "sled", version = "*" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = [
    # "https://github.com/PistonDevelopers/conrod",
    "https://github.com/adumbidiot/conrod",
    "https://github.com/Thinkofname/steamworks-rs",
    # "https://github.com/adumbidiot/steamworks-rs",
    "https://github.com/nathaniel-daniel/glutin_window",
]
