name: Rust
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
    STEAM_SDK_LOCATION: ./steamworks-sdk/steamworks_sdk_148a/sdk
jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy 
          override: true
      - name: Checkout Private Steamworks SDK
        uses: actions/checkout@v2
        with:
          repository: adumbidiot/private-steamworks-sdk
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          path: steamworks-sdk
      - name: Install Scoop
        run: |
            iwr -useb get.scoop.sh | iex
            echo "::add-path::$($HOME)/scoop/shims"
      - name: Install LLVM
        run: |
            scoop install llvm
            echo "::set-env name=LIBCLANG_PATH::$($HOME)/scoop/apps/llvm/current/bin"
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: '-- --check --color always'
      - name: Fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: '--tests -- -D warnings'
      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v1
# TODO: Figure out automatic building with steamworks
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build
#        run: cargo build --verbose
#      - name: Run tests
#        run: cargo test --all --verbose